name: London Samurai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09139785
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#717275'
    - '#9D0A0E'
    - '#39393A'
  brandStrength: 1
  lightness: 0.4336918
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
