collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.09139785
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.4336918
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#717275'
    - '#9D0A0E'
    - '#39393A'
  rhythmicContrast: 0.8422939
layout_spectrum: 1
name: London Samurai
